(define (fact n) (if (= n 0) 1 (* n (fact (- n 1)))))
(fact 10)
(define (fib n) (if (< n 2) n (+ (fib (- n 1)) (fib (- n 2)))))
(fib 15)
(define (sum-to n) (if (= n 0) 0 (+ n (sum-to (- n 1)))))
(sum-to 100)
