(define (map f xs)
  (if (null? xs) '() (cons (f (car xs)) (map f (cdr xs)))))
(define (filter pred xs)
  (cond ((null? xs) '())
        ((pred (car xs)) (cons (car xs) (filter pred (cdr xs))))
        (else (filter pred (cdr xs)))))
(define (square x) (* x x))
(map square '(1 2 3 4 5))
(filter (lambda (x) (> x 3)) '(1 5 2 6 3 7))
(map (lambda (x) (if (even? x) (* x 2) x)) '(1 2 3 4))
